HalcyonApparelsMVC/Controllers/MarketingController.cs
using FluentEmail.Core;
using HalcyonApparelsMVC.DTO;
using HalcyonApparelsMVC.Interfaces;
using HalcyonApparelsMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HalcyonApparelsMVC.Controllers
{
    [Authorize]
    public class MarketingController : Controller
    {

        private readonly IMailSender _mailSender;
        private readonly IConfiguration _config;
      
        public MarketingController(IMailSender mailSender, IConfiguration config, ISalesforceData salesforcedata)
        {
            _mailSender = mailSender;
            _config = config;
            
        }


        [HttpGet("CustomerView")]
        public List<GetCustomer> CustomerView()
        {
            HttpClientHandler clienthandler = new HttpClientHandler();
            clienthandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslpolicyerrors) => { return true; };

            HttpClient client = new HttpClient(clienthandler);
            client.BaseAddress = new Uri(_config["WebConfig:UserApi"]);
            List<GetCustomer>? customer = new List<GetCustomer>();

            HttpResponseMessage res = client.GetAsync("api/Mapping/GetCustomer").Result;
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                customer = JsonConvert.DeserializeObject<List<GetCustomer>>(result);
            }
            return customer;

        }



        [HttpGet]
        public IActionResult MarketingView()
        {
            
            HttpClientHandler clienthandler = new HttpClientHandler();
            clienthandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslpolicyerrors) => { return true; };

            HttpClient client = new HttpClient(clienthandler);
            client.BaseAddress = new Uri(_config["WebConfig:UserApi"]);
            List<AccessoryDetailsMVC>? acctype = new List<AccessoryDetailsMVC>();
            List<ProductType>? ptype = new List<ProductType>();

            HttpResponseMessage res = client.GetAsync("api/Mapping/GetAccessoryType").Result;

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                acctype = JsonConvert.DeserializeObject<List<AccessoryDetailsMVC>>(result);
            }

            HttpResponseMessage resultp = client.GetAsync("api/Mapping/GetProductType").Result;
            if (res.IsSuccessStatusCode)
            {
                var result = resultp.Content.ReadAsStringAsync().Result;
                ptype = JsonConvert.DeserializeObject<List<ProductType>>(result);
            }
            ViewBag.acclist = acctype.Select(c => c.AccessoryType).ToList().Distinct();
            ViewBag.ptypelist = ptype.Select(c => c.ProdType).ToList();
            
            return View();
           

        }



        [HttpPost]
        public async Task<IActionResult> MarketingView(MapDTO map)
        {
           
            HttpClientHandler clienthandler = new HttpClientHandler();
            clienthandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslpolicyerrors) => { return true; };
            HttpClient client = new HttpClient(clienthandler);
            client.BaseAddress = new Uri(_config["WebConfig:UserApi"]);

            var postTask = client.PostAsJsonAsync<MapDTO>("api/Mapping/PostMarketing", map);

            postTask.Wait();
            var Result = postTask.Result;
            if (Result.IsSuccessStatusCode)
            {
                TempData["AlertMessage"] = " Mapping updated ";
                return RedirectToAction("AccessoryView", "Home");

            }

            return View();
        }


    

        public async Task<IActionResult> Mail([FromServices] IFluentEmail mailer)
        {
            HttpClientHandler clienthandler = new HttpClientHandler();
            clienthandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslpolicyerrors) => { return true; };

            HttpClient client = new HttpClient(clienthandler);
            client.BaseAddress = new Uri(_config["WebConfig:UserApi"]);
            List<GetCustomer>? customer = new List<GetCustomer>();

            HttpResponseMessage res = client.GetAsync("api/Mapping/GetCustomer").Result;

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                customer = JsonConvert.DeserializeObject<List<GetCustomer>>(result);
            }
            List<MarketingList>? mailtype = new List<MarketingList>();
            HttpResponseMessage resmail = client.GetAsync("api/Mapping/GetMailingList").Result;

            if (resmail.IsSuccessStatusCode)
            {
                var result = resmail.Content.ReadAsStringAsync().Result;
                mailtype = JsonConvert.DeserializeObject<List<MarketingList>>(result);
            }
  
            _mailSender.SendBulkMail(mailtype);
            return RedirectToAction("AccessoryView", "Home");
            
        }


    }
}

HalcyonApparelsMVC/Views/Marketing/Email.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

HalcyonApparelsMVC/Views/Marketing/Mail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

HalcyonApparelsMVC/Views/Marketing/MarketingView.cshtml
@model HalcyonApparelsMVC.DTO.MapDTO
@{
    ViewData["Title"] = "MarketingView";
    var aclist = ViewBag.acclist as List<string>;
}


<h3 style="color: black; margin-top:25px; margin-bottom:30px;">Marketing</h3>

<div class="wrap">
    <form asp-action="MarketingView" method="post">
    <select name="accessorytype" asp-for="accessorytype" asp-items="new SelectList(ViewBag.acclist)">
     
    </select>
        <select name="productType" asp-for="productType" asp-items="new SelectList(ViewBag.ptypelist)">
    </select>
    <div style="margin-top:15px;">

    <input type="submit" value="Submit" class="btn btn-primary" data-inline="true" />
    </div>

       @* <i class="bi bi bi-file-plus-fill" onclick=" location.href='@Url.Action("AccessoryTypeView", "Marketing")'" style="color:blue;"></i>*@
</form>

    @*<div style="margin-top: 25px;">

        <button type="button" value="Send Mails" class="btn btn-primary"  onclick=" location.href='@Url.Action("Mail", "Marketing")' ">Send Emails</button>
    </div>*@
</div>

HalcyonApparelsMVC/Views/Marketing/OrderView.cshtml
@model IEnumerable<HalcyonApparelsMVC.Models.GetOrder>

@{
    ViewData["Title"] = "OrderView";
}

<h1>OrderView</h1>

<div>
    <h4>GetOrder</h4>
    <hr />
    @foreach (var item in Model)
    {
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => item.Parent_Order_Id__c)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => item.Parent_Order_Id__c)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => item.ordered_Date__c)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => item.ordered_Date__c)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => item.Product_Type__c)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => item.Product_Type__c)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => item.Contact__c)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => item.Contact__c)
            </dd>
        </dl>
    }
    
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>